export { default as Home } from './Home';
export { default as Booking } from './Booking';
export { default as Customer } from './Customer';
export { default as Room } from './Room';
export { default as Setting } from './Setting';
export { default as Staff } from './Staff';
export { default as Statistical } from './Statistical';
export { default as Support } from './Support';
export { default as Login } from './Login';
